---
development:
  # dialect: postgres
  # database: scdsbackend_development
  # user: postgres
  # password: 1
  # host: 127.0.0.1
  # pool: 5
  dialect: postgres
  database: postgres
  user: postgres.hhmheadfyqlkuxxzofhb
  password: xLyYb,?GYGj-P6d
  host: aws-0-ap-southeast-1.pooler.supabase.com
  pool: 5
  port: 5432

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/scdsbackend_test?sslmode=disable"}}

production:
  dialect: postgres
  database: postgres
  user: postgres.hhmheadfyqlkuxxzofhb
  password: xLyYb,?GYGj-P6d
  host: aws-0-ap-southeast-1.pooler.supabase.com
  pool: 5
  port: 5432
  # url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/scdsbackend_production?sslmode=disable"}}
